Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)
Building a DBG and calling unitigs within...
Generating pyseer file...
